#cloud-config
autoinstall:
  version: 1
  locale: en_US
  keyboard:
    layout: en
  network:
    version: 2
    renderer: networkd
    wifis:
      wlan0:
        access-points:
          "CAFE-ETZ-TERASSA-5G":
            password: "20222022"
        dhcp4: true
        optional: true
  storage:
    layout:
      name: lvm
  identity:
    hostname: ubuntu
    username: ubuntu
    password: "$6$xyz$encrypted-password"
  ssh:
    install-server: true
  packages:
    - linux-firmware
    - firmware-b43-installer
    - network-manager
  late-commands:
    - curtin in-target -- apt-get update
    - curtin in-target -- apt-get upgrade -y
    - curtin in-target -- apt-get install -y vim
    - curtin in-target -- apt-get install -y nc
    - curtin in-target -- systemctl enable NetworkManager
    - curtin in-target -- systemctl start NetworkManager
    - curtin in-target -- netplan apply
